{
 "title": "Uponor FBH Wohnhaus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heizleistung kW",
   "type": "gauge",
   "description": "wieviel Fläche und wieviel kW ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizleistung" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_Allgemein" }
     ]
    }
   ]
  },
  {
   "title": "Heizfläche m²",
   "type": "gauge",
   "description": "wieviel Fläche und wieviel kW ",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "m²",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizfläche" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_Allgemein" }
     ]
    }
   ]
  },
  {
   "title": "Soll-Temperaturen",
   "type": "stat",
   "gridPos": { "h": 22, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Diele" }
     ]
    },
    {
     "alias": "DG-Marius",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Seeblick" }
     ]
    },
    {
     "alias": "DG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Wellness" }
     ]
    },
    {
     "alias": "EG-Elternbad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Elternbad" }
     ]
    },
    {
     "alias": "EG-Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Kueche" }
     ]
    },
    {
     "alias": "EG-Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Wohnzimmer" }
     ]
    },
    {
     "alias": "EG-Schlafzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Schlafzimmer" }
     ]
    },
    {
     "alias": "EG-Ankleide",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Ankleide" }
     ]
    },
    {
     "alias": "UG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Diele" }
     ]
    },
    {
     "alias": "UG-Seeblick",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Wohnzimmer" }
     ]
    },
    {
     "alias": "UG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestebad" }
     ]
    },
    {
     "alias": "UG-Putzlager",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestekammer" }
     ]
    },
    {
     "alias": "UG-Stiefelraum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Stiefelraum" }
     ]
    }
   ]
  },
  {
   "title": "Abweichung",
   "type": "stat",
   "description": "wieviel Grad entfernt vom Soll",
   "gridPos": { "h": 22, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_DG-Diele') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Diele" }
     ]
    },
    {
     "alias": "DG-Marius",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_DG-Seeblick') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Seeblick" }
     ]
    },
    {
     "alias": "DG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_DG-Wellness') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Wellness" }
     ]
    },
    {
     "alias": "EG-Elternbad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_EG-Elternbad') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Elternbad" }
     ]
    },
    {
     "alias": "EG-Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_EG-Kueche') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Kueche" }
     ]
    },
    {
     "alias": "EG-Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_EG-Wohnzimmer') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Wohnzimmer" }
     ]
    },
    {
     "alias": "EG-Schlafzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_EG-Schlafzimmer') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Schlafzimmer" }
     ]
    },
    {
     "alias": "EG-Ankleide",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_EG-Ankleide') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Ankleide" }
     ]
    },
    {
     "alias": "UG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_UG-Diele') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Diele" }
     ]
    },
    {
     "alias": "UG-Seeblick",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_UG-Wohnzimmer') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Wohnzimmer" }
     ]
    },
    {
     "alias": "UG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_UG-Gaestebad') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestebad" }
     ]
    },
    {
     "alias": "UG-Putzlager",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_UG-Gaestekammer') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestekammer" }
     ]
    },
    {
     "alias": "UG-Stiefelraum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "query": "SELECT last(\"Isttemp\")-last(\"Solltemp\") FROM \"autogen\".\"uponor\" WHERE (\"bereich\" = 'KM4_UG-Stiefelraum') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solltemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Stiefelraum" }
     ]
    }
   ]
  },
  {
   "title": "Raumventile",
   "type": "stat",
   "description": "Welcher Raum wird aktuell beheizt",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Diele" }
     ]
    },
    {
     "alias": "DG-Marius",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Seeblick" }
     ]
    },
    {
     "alias": "DG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_DG-Wellness" }
     ]
    }
   ]
  },
  {
   "title": "Vorlauftemp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 7 },
   "targets": [
    {
     "alias": "HK1 Vorl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heizung",
     "select": [
      [
       { "params": [ "hk1_L_flowtemp_act" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "hk1" }
     ]
    }
   ]
  },
  {
   "title": "Raumventile Wohnung",
   "type": "stat",
   "description": "Welcher Raum wird aktuell beheizt",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Elternbad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Elternbad" }
     ]
    },
    {
     "alias": "EG-Küche",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Kueche" }
     ]
    },
    {
     "alias": "EG-Wohnzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Wohnzimmer" }
     ]
    },
    {
     "alias": "EG-Schlafzimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Schlafzimmer" }
     ]
    },
    {
     "alias": "EG-Ankleide",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_EG-Ankleide" }
     ]
    }
   ]
  },
  {
   "title": "Raumventile UG",
   "type": "stat",
   "description": "Welcher Raum wird aktuell beheizt",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UG-Diele",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Diele" }
     ]
    },
    {
     "alias": "UG-Seeblick WZ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Wohnzimmer" }
     ]
    },
    {
     "alias": "UG-Bad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestebad" }
     ]
    },
    {
     "alias": "UG-Putzlager",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Gaestekammer" }
     ]
    },
    {
     "alias": "UG-Stiefelraum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uponor",
     "select": [
      [
       { "params": [ "Heizt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "bereich", "operator": "=", "value": "KM4_UG-Stiefelraum" }
     ]
    }
   ]
  }
 ]
}